# API Collection For RSQ4

RSQ4 - Main Question: Which generation is the strongest?

Sub question: What trends can be seen over the generations (number of pokémon, types, base stat distribution)?

In this notebook, I will use the raw generation CSV file that I called and find each Pokemon and its given generation and combine it with the our main pokémon information gathered from RSQ3.

**A generation is a grouping of the Pokémon games that separates them based on the Pokémon they include. In each generation, a new set of Pokémon, region, moves, and Abilities can be added that did not exist in the previously released generations. Currently, there are 8 generations of Pokémon.**

In Pokémon, the ranges of each generation (based on Pokémon ID) are as follows:

            Generation 1: 1 - 151
            Generation 2: 152 - 251
            Generation 3: 252 - 386
            Generation 4: 387 - 493
            Generation 5: 494 - 649
            Generation 6: 650 - 721
            Generation 7: 722 - 809
            Generation 8: 810 - 898

## Task 1: Imports and Local Files

Below are the necessary imports needed for this notebook.

In [1]:
import pandas as pd

Here I have the raw information that I called from the PokéAPI which contains the generations and the pokemons within that generation. I turn this local CSV file into a dataframe.

In [2]:
df_gen_raw = pd.read_csv("401_all_generation_data.csv")
df_gen_raw

,abilities,id,main_region,moves,name,names,pokemon_species,types,version_groups
0,[],1,"{'name': 'kanto', 'url': 'https://pokeapi.co/a...","[{'name': 'pound', 'url': 'https://pokeapi.co/...",generation-i,"[{'language': {'name': 'ja-Hrkt', 'url': 'http...","[{'name': 'bulbasaur', 'url': 'https://pokeapi...","[{'name': 'normal', 'url': 'https://pokeapi.co...","[{'name': 'red-blue', 'url': 'https://pokeapi...."
1,[],2,"{'name': 'johto', 'url': 'https://pokeapi.co/a...","[{'name': 'sketch', 'url': 'https://pokeapi.co...",generation-ii,"[{'language': {'name': 'ja-Hrkt', 'url': 'http...","[{'name': 'chikorita', 'url': 'https://pokeapi...","[{'name': 'steel', 'url': 'https://pokeapi.co/...","[{'name': 'gold-silver', 'url': 'https://pokea..."
2,"[{'name': 'stench', 'url': 'https://pokeapi.co...",3,"{'name': 'hoenn', 'url': 'https://pokeapi.co/a...","[{'name': 'fake-out', 'url': 'https://pokeapi....",generation-iii,"[{'language': {'name': 'ja-Hrkt', 'url': 'http...","[{'name': 'treecko', 'url': 'https://pokeapi.c...","[{'name': 'shadow', 'url': 'https://pokeapi.co...","[{'name': 'ruby-sapphire', 'url': 'https://pok..."
3,"[{'name': 'tangled-feet', 'url': 'https://poke...",4,"{'name': 'sinnoh', 'url': 'https://pokeapi.co/...","[{'name': 'roost', 'url': 'https://pokeapi.co/...",generation-iv,"[{'language': {'name': 'ja-Hrkt', 'url': 'http...","[{'name': 'turtwig', 'url': 'https://pokeapi.c...",[],"[{'name': 'diamond-pearl', 'url': 'https://pok..."
4,"[{'name': 'pickpocket', 'url': 'https://pokeap...",5,"{'name': 'unova', 'url': 'https://pokeapi.co/a...","[{'name': 'hone-claws', 'url': 'https://pokeap...",generation-v,"[{'language': {'name': 'ja-Hrkt', 'url': 'http...","[{'name': 'victini', 'url': 'https://pokeapi.c...",[],"[{'name': 'black-white', 'url': 'https://pokea..."
5,"[{'name': 'aroma-veil', 'url': 'https://pokeap...",6,"{'name': 'kalos', 'url': 'https://pokeapi.co/a...","[{'name': 'flying-press', 'url': 'https://poke...",generation-vi,"[{'language': {'name': 'ja-Hrkt', 'url': 'http...","[{'name': 'chespin', 'url': 'https://pokeapi.c...","[{'name': 'fairy', 'url': 'https://pokeapi.co/...","[{'name': 'x-y', 'url': 'https://pokeapi.co/ap..."
6,"[{'name': 'stamina', 'url': 'https://pokeapi.c...",7,"{'name': 'alola', 'url': 'https://pokeapi.co/a...","[{'name': 'breakneck-blitz--physical', 'url': ...",generation-vii,"[{'language': {'name': 'ja-Hrkt', 'url': 'http...","[{'name': 'rowlet', 'url': 'https://pokeapi.co...",[],"[{'name': 'sun-moon', 'url': 'https://pokeapi...."
7,"[{'name': 'intrepid-sword', 'url': 'https://po...",8,"{'name': 'galar', 'url': 'https://pokeapi.co/a...","[{'name': 'max-guard', 'url': 'https://pokeapi...",generation-viii,"[{'language': {'name': 'en', 'url': 'https://p...","[{'name': 'grookey', 'url': 'https://pokeapi.c...",[],"[{'name': 'sword-shield', 'url': 'https://poke..."

I also use the local file I created from RSQ3 which contains each individual pokemon and its relevant information, including stats. I turned this into a dataframe. My intention for this dataframe is to create a new column which will indicate the generation each pokemon is in by merging my findings.

In [3]:
df_poke_raw = pd.read_csv("301_all_pokemon_data_base_stats_collect.csv")
df_poke_raw

,base_experience,height,id,name,order,weight,ABILITY1,ABILITY2,HIDDEN_ABILITY,TYPE1,TYPE2,HP,ATTACK,DEFENSE,SPECIAL_ATTACK,SPECIAL_DEFENSE,SPEED,TOTAL_STAT
0,64,7,1,bulbasaur,1,69,overgrow,none,chlorophyll,grass,poison,45,49,49,65,65,45,318
1,142,10,2,ivysaur,2,130,overgrow,none,chlorophyll,grass,poison,60,62,63,80,80,60,405
2,236,20,3,venusaur,3,1000,overgrow,none,chlorophyll,grass,poison,80,82,83,100,100,80,525
3,62,6,4,charmander,5,85,blaze,none,solar-power,fire,none,39,52,43,60,50,65,309
4,142,11,5,charmeleon,6,190,blaze,none,solar-power,fire,none,58,64,58,80,65,80,405
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
893,290,12,894,regieleki,-1,1450,transistor,none,none,electric,none,80,100,50,100,50,200,580
894,290,21,895,regidrago,-1,2000,dragons-maw,none,none,dragon,none,200,100,50,100,50,80,580
895,290,22,896,glastrier,-1,8000,chilling-neigh,none,none,ice,none,100,145,130,65,110,30,580
896,290,20,897,spectrier,-1,445,grim-neigh,none,none,ghost,none,100,65,60,145,80,130,580
897,250,11,898,calyrex,-1,77,unnerve,none,none,psychic,grass,100,80,80,80,80,80,500

## Task 2: Finding the Generations

The relevant column I need to access is the 'pokemon_species' columns as it contains the name of all the pokémon in the generation. So, I loop through the 8 generations from the geenration dataframe and gather every name in said generation and place them into an empty list called 'names'. At the same time, I have a generation counter that I add to its own list called 'gen'. 

The lists for the pokemon and the generation number are then put into a zipped list so they can be displayed as a dataframe.

In [4]:
#empty lists to collect 1) the pokemons name + 2) generation of the pokemon
names = []
gen = []
    
#loops through 8 generations
for x in range(8):
    genx = df_gen_raw["pokemon_species"][x]
    #turns the dataframe column into a list, making it possible to loop through every name
    genx = eval(genx)
    generation = x+1 #generation range of 1-8, to be appended to list
    #loops through pokemon names per generation
    for gx in genx:
        pokeName = gx["name"]
        names.append(pokeName)
        gen.append(generation)

In [5]:
zippedList =  list(zip(names, gen))

In [6]:
df_gen_no = pd.DataFrame(zippedList, columns = ['name', 'GENERATION_NO'])
df_gen_no

            name  GENERATION_NO
0      bulbasaur              1
1     charmander              1
2       squirtle              1
3       caterpie              1
4         weedle              1
..           ...            ...
893    dragapult              8
894      urshifu              8
895  corviknight              8
896     appletun              8
897    hatterene              8

[898 rows x 2 columns]

## Task 3: Merging Data

Now that we have the pokémons generation number, I want to combine the pokémon dataframe to the dataframe with the generation number. Both dataframes have a name column, thus we merge on this column and create a new dataframe which has all of the pokémons information with the addition of its generation number.

In [7]:
df_pokeGen = df_poke_raw.merge(df_gen_no, on='name',how= 'left')

In [8]:
df_pokeGen = df_pokeGen.set_index(df_pokeGen["id"])

In [9]:
df_pokeGen

,base_experience,height,id,name,order,weight,ABILITY1,ABILITY2,HIDDEN_ABILITY,TYPE1,TYPE2,HP,ATTACK,DEFENSE,SPECIAL_ATTACK,SPECIAL_DEFENSE,SPEED,TOTAL_STAT,GENERATION_NO
id,,,,,,,,,,,,,,,,,,,
1,64,7,1,bulbasaur,1,69,overgrow,none,chlorophyll,grass,poison,45,49,49,65,65,45,318,1.0
2,142,10,2,ivysaur,2,130,overgrow,none,chlorophyll,grass,poison,60,62,63,80,80,60,405,1.0
3,236,20,3,venusaur,3,1000,overgrow,none,chlorophyll,grass,poison,80,82,83,100,100,80,525,1.0
4,62,6,4,charmander,5,85,blaze,none,solar-power,fire,none,39,52,43,60,50,65,309,1.0
5,142,11,5,charmeleon,6,190,blaze,none,solar-power,fire,none,58,64,58,80,65,80,405,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
894,290,12,894,regieleki,-1,1450,transistor,none,none,electric,none,80,100,50,100,50,200,580,8.0
895,290,21,895,regidrago,-1,2000,dragons-maw,none,none,dragon,none,200,100,50,100,50,80,580,8.0
896,290,22,896,glastrier,-1,8000,chilling-neigh,none,none,ice,none,100,145,130,65,110,30,580,8.0
897,290,20,897,spectrier,-1,445,grim-neigh,none,none,ghost,none,100,65,60,145,80,130,580,8.0
898,250,11,898,calyrex,-1,77,unnerve,none,none,psychic,grass,100,80,80,80,80,80,500,8.0

However, it appears that some of the pokémon from the pokémon dataframe were labelled incorrectly. As we can see, as I check the Generation number column for any null values, 26 pokemon come up without a generation. 

We can see from the 'name' column that all of these names were hyphenated by mistake, whereas in the generation number dataframe they were not hyphenated. As a result, there was no clear match and they ended up without a generation number.

    For example, the pokemon 'deoxys' (id 386) was named 'deoxys-normal'.

In [10]:
df_pokeGen[df_pokeGen["GENERATION_NO"].isna()]

,base_experience,height,id,name,order,weight,ABILITY1,ABILITY2,HIDDEN_ABILITY,TYPE1,TYPE2,HP,ATTACK,DEFENSE,SPECIAL_ATTACK,SPECIAL_DEFENSE,SPEED,TOTAL_STAT,GENERATION_NO
id,,,,,,,,,,,,,,,,,,,
386,270,17,386,deoxys-normal,496,608,pressure,none,none,psychic,none,50,150,50,150,50,150,600,NaN
413,148,5,413,wormadam-plant,524,65,anticipation,none,overcoat,bug,grass,60,59,85,79,105,36,424,NaN
487,306,45,487,giratina-altered,582,7500,pressure,none,telepathy,ghost,dragon,150,100,120,100,120,90,680,NaN
492,270,2,492,shaymin-land,588,21,natural-cure,none,none,grass,none,100,100,100,100,100,100,600,NaN
550,161,10,550,basculin-red-striped,648,180,reckless,adaptability,mold-breaker,water,none,70,92,65,80,55,98,460,NaN
555,168,13,555,darmanitan-standard,654,929,sheer-force,none,zen-mode,fire,none,105,140,55,30,55,95,480,NaN
641,261,15,641,tornadus-incarnate,741,630,prankster,none,defiant,flying,none,79,115,70,125,80,111,580,NaN
642,261,15,642,thundurus-incarnate,743,610,prankster,none,defiant,electric,flying,79,115,70,125,80,111,580,NaN
645,270,15,645,landorus-incarnate,747,680,sand-force,none,sheer-force,ground,flying,89,125,90,115,80,101,600,NaN
647,261,14,647,keldeo-ordinary,752,485,justified,none,none,water,fighting,91,72,90,129,90,108,580,NaN
648,270,6,648,meloetta-aria,754,65,serene-grace,none,none,normal,psychic,100,77,77,128,128,90,600,NaN
678,163,6,678,meowstic-male,788,85,keen-eye,infiltrator,prankster,psychic,none,74,48,76,83,81,104,466,NaN
681,234,17,681,aegislash-shield,792,530,stance-change,none,none,steel,ghost,60,50,140,50,140,60,500,NaN
710,67,4,710,pumpkaboo-average,821,50,pickup,frisk,insomnia,ghost,grass,49,66,70,44,55,51,335,NaN
711,173,9,711,gourgeist-average,825,125,pickup,frisk,insomnia,ghost,grass,65,90,122,58,75,84,494,NaN
741,167,6,741,oricorio-baile,865,34,dancer,none,none,fire,flying,75,70,70,98,70,93,476,NaN
745,170,8,745,lycanroc-midday,874,250,keen-eye,sand-rush,steadfast,rock,none,75,115,65,55,65,112,487,NaN
746,61,2,746,wishiwashi-solo,877,3,schooling,none,none,water,none,45,20,20,25,25,40,175,NaN
774,154,3,774,minior-red-meteor,909,400,shields-down,none,none,rock,flying,60,60,100,60,100,60,440,NaN
778,167,2,778,mimikyu-disguised,927,7,disguise,none,none,ghost,fairy,55,90,80,50,105,96,476,NaN
849,176,16,849,toxtricity-amped,-1,400,punk-rock,plus,technician,electric,poison,75,98,70,114,70,75,502,NaN
875,165,14,875,eiscue-ice,-1,890,ice-face,none,none,ice,none,75,80,110,65,90,50,470,NaN
876,166,9,876,indeedee-male,-1,280,inner-focus,synchronize,psychic-surge,psychic,normal,60,65,55,105,95,95,475,NaN
888,335,28,888,zacian-hero,-1,1100,intrepid-sword,none,none,fairy,none,92,130,115,80,115,138,670,NaN
889,335,29,889,zamazenta-hero,-1,2100,dauntless-shield,none,none,fighting,none,92,130,115,80,115,138,670,NaN
892,275,19,892,urshifu-single-strike,-1,1050,unseen-fist,none,none,fighting,dark,100,130,100,63,60,97,550,NaN

After looking through the 26 pokemon without a generation, I confirmed that it would be safe to fill in these null values by copying the previous value and entering it into the null index. Since the pokemon are in ID order which matches their generation order this makes this method easy to imploy.

I ensured that these pokemons were not the first pokemon in a given generation since this would cause an incorrect result.

In [11]:
df_pokeGen = df_pokeGen.fillna(method ='pad')

To confirm that there are no longer any empty values I repeat the test to see if there are any null Generation numbers.

In [12]:
df_pokeGen[df_pokeGen["GENERATION_NO"].isna()]

Empty DataFrame
Columns: [base_experience, height, id, name, order, weight, ABILITY1, ABILITY2, HIDDEN_ABILITY, TYPE1, TYPE2, HP, ATTACK, DEFENSE, SPECIAL_ATTACK, SPECIAL_DEFENSE, SPEED, TOTAL_STAT, GENERATION_NO]
Index: []

Finally, I enter one of the pokemons who were given a hyphenated name by mistake. In this instance, I checked on deoxys(-normal) and can confirm that their generation (Generation 3) was entered correctly.

In [13]:
df_pokeGen[df_pokeGen["name"] == 'deoxys-normal']

,base_experience,height,id,name,order,weight,ABILITY1,ABILITY2,HIDDEN_ABILITY,TYPE1,TYPE2,HP,ATTACK,DEFENSE,SPECIAL_ATTACK,SPECIAL_DEFENSE,SPEED,TOTAL_STAT,GENERATION_NO
id,,,,,,,,,,,,,,,,,,,
386,270,17,386,deoxys-normal,496,608,pressure,none,none,psychic,none,50,150,50,150,50,150,600,3.0

## Task 4: Save Local File

I save the found information into a CSV local file. This file will contain the pokemons information, its indivdual stats and total stats, and its assigned generation.

In [15]:
df_pokeGen.to_csv("401_all_generation_pokemon_data.csv", index=False)
df_pokeGen.shape

(898, 19)